defmodule SonetLib.TestRepo.Migrations.Genesis do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :email, :citext, null: false
    end

    create unique_index(:user, [:email], name: "user_unique_email_index")

    create table(:store, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :handle, :citext, null: false

      add :user_id,
          references(:user,
            column: :id,
            name: "store_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:store, [:handle], name: "store_unique_handle_index")
  end

  def down do
    drop_if_exists unique_index(:store, [:handle], name: "store_unique_handle_index")

    drop constraint(:store, "store_user_id_fkey")

    drop table(:store)

    drop_if_exists unique_index(:user, [:email], name: "user_unique_email_index")

    drop table(:user)
  end
end
